export const UPDATE_NAME = 'UPDATE_NAME';

/** Tasks Actions **/
export const TASKS_ADD_TASK = 'TASKS_ADD_TASK';
export const TASKS_TOGGLE_EDIT_TASK = 'TASKS_TOGGLE_EDIT_TASK';
export const TASKS_SAVE_EDIT = 'TASKS_SAVE_EDIT';
export const TASKS_CANCEL_EDIT = 'TASKS_CANCEL_EDIT';
export const TASKS_REMOVE_TASK = 'TASKS_REMOVE_TASK';